# Generated by Django 6.0.1 on 2026-02-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('valorAluguel', models.DecimalField(decimal_places=7, max_digits=10)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('LOCADOR', 'Locador'), ('LOCATARIO', 'Locatário')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datainicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('valor', models.DecimalField(decimal_places=10, max_digits=20)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='api.imovel')),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locador', to='api.usuario')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locatario', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=10, max_digits=20)),
                ('status', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='api.contrato')),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='locador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to='api.usuario'),
        ),
    ]
